### ISSUE TITLE
Offline Message from Maryann Martone: Why are none of these terms annotated e

### ISSUE THREAD

**Issue by SciCrunch-Synapse** [SciCrunch/sparc-curation#111]
This Github issue is synchronized with Zendesk:

**Ticket ID:** [#49948](https://scicrunch.zendesk.com/agent/tickets/49948)
**Requester:** maryann@ncmir.ucsd.edu
**Community Name:** fdi_lab
**URL:** 

**Original ticket description:**

<blockquote><div class="zd-comment" dir="auto"><p dir="auto">From: Maryann Martone &lt;<a href="mailto:mmartone@ucsd.edu" rel="noreferrer">mmartone@ucsd.edu</a>&gt;
<br>Phone: 
<br>Location: San Diego, United States
<br>URL: <a href="https://scicrunch.org/scicrunch/interlex/view/ilx_0793115?searchTerm=fiducial" target="_blank" rel="nofollow noreferrer">https://scicrunch.org/scicrunch/interlex/view/ilx_0793115?searchTerm=fiducial</a>
<br>Department: </p>

<p dir="auto">Why are none of these terms annotated either as part of SPARC nor related to a parent term that would identify them as fiducial markers.  Please have Troy fix all fo these.  </p>

<p dir="auto">----
<br>Zopim
<br><a href="https://www.zopim.com" target="_blank" rel="nofollow noreferrer">https://www.zopim.com</a></p></div></blockquote>

**Comment by tgbugs** [comment]
These are now in the relevant termsets.
