### ISSUE TITLE
No relationship between subject and data set?

### ISSUE THREAD

**Issue by memartone** [SciCrunch/sparc-curation#18]
Hi Tom:
Jeff and I are trying different ways to view the instance graph and we can't find any relationship between the subject and the data set, so we can't see all the subjects belonging to a data set.  There is a relationship between sample and subject and the data set shows the number of subjects and number of samples.  Can you please explain?

**Comment by memartone** [comment]
So in the case of subjects where there are no samples, e.g., sub-2013-05-21, there is no relationship at all between the subject and the data set.  We see that if there is a sample, you can get from sample to subject and sample to data set.  But in the above case, there is no explicit relationship.

**Comment by tgbugs** [comment]
There is currently no explicit relationship between subjects/samples and datasets, it is implicit in the identifiers (e.g. `<https://api.blackfynn.io/datasets/N:dataset:0a5a2827-2b39-4085-87ea-2b7fbbe27cc8/subjects/sub-2013-05-21>`) and is also implicit in the individual dataset files where only subjects for that dataset are included in the dataset ttl file.

This is clearly undesirable. I will add an explicit relationship between samples and subjects on the dataset which will be `TEMP:hasParticipant`, not quite the correct name for the relationship but it will do for now.

Relatedly, In the json file this is implicit in the nesting structure.

**Comment by jgrethe** [comment]
One thing we noted as well was that not all samples had the explicit relationship to the subject they came from.  It seemed to show up in the first sample for a subject and then the subsequent samples didn’t have that relationship. While some sets of samples all had the information.  We think this is probably coming from the spreadsheet where perhaps the first Subject value was inserted and the remainder of the values were left blank until the next Subject.  So this is probably a curation thing - but wanted to add this to the discussion.

**Comment by tgbugs** [comment]
Resolved with better predicates via https://github.com/SciCrunch/sparc-curation/commit/d0013e071b54496e75bbbae44ccfe26f876f2969.
