### ISSUE TITLE
Error in latest .ttl file

### ISSUE THREAD

**Issue by memartone** [SciCrunch/sparc-curation#19]
When I try to open it in Protege, it says: org.xml.sax.SAXParseException; systemId: file:/Users/maryannmartone/Downloads/curation-export-2.ttl; lineNumber: 1; columnNumber: 1; Content is not allowed in prolog.

When I try to load it in GraphDB, it says:  curation-export-2.ttl
    RDF Parse Error: Illegal subject value: "n/a" [line 36]

**Comment by jgrethe** [comment]
I was getting the same error with the GraphDB load.  If I just removed that line the load produced no errors.

**Comment by tgbugs** [comment]
This has been fixed. There was a case where someone included "n/a" for an orcid and it was being serialized as a subject in the graph. Now, when a value that would be used as an identifier in the graph fails to validate in the json schema that part of the record is excluded.
