### ISSUE TITLE
Pulling metadata for publications

### ISSUE THREAD

**Issue by memartone** [SciCrunch/sparc-curation#21]
Hi Tom:
We spoke a few weeks ago about you pulling the article metadata from the DOI's we get in our data descriptions and including them in the .ttl file.  Apparently that is a milestone for which we are responsible.  Can you make sure that is available in the next .ttl file?

**Comment by tgbugs** [comment]
This has been done since https://cassava.ucsd.edu/sparc/archive/exports/2020-02-07T14%3A21%3A44%2C603595-08%3A00/curation-export.ttl.
