### ISSUE TITLE
Additional Items to Pull in during processing

### ISSUE THREAD

**Issue by jgrethe** [SciCrunch/sparc-curation#22]
The JSON export has a number of links (URIs) that should probably be processed by the curation script.  The Preferred Label should be included with the URI. Namely:

Techniques (http://uri.interlex.org/tgbugs/uris/readable/technique/anestheticAdministration)
Organ (http://purl.obolibrary.org/obo/UBERON_0000945)
Affiliation RORs

Also, the Protocol Information (Name, Description, etc) is not in the TTL/JSON export.  That should probably be included as well.

There are probably more, but this is a start

**Comment by tgbugs** [comment]
Organs, affiliations, dois, orcids, and protocols are in (see https://github.com/SciCrunch/sparc-curation/issues/25#issuecomment-632641868). I need to normalize the `contributor_affiliation` field which sometimes has a ror in it if @ankap2 filled it in.

Techniques should be in next release once I merge the [methods](https://github.com/SciCrunch/NIF-Ontology/blob/methods/ttl/methods.ttl) branch into dev.

**Comment by tgbugs** [comment]
These are included now (and have been for a while).
