### ISSUE TITLE
Question about https://api.blackfynn.io/datasets/N:dataset:dae2fef9-05e6-418f-8374-3af267643340/samples/sam-3

### ISSUE THREAD

**Issue by memartone** [SciCrunch/sparc-curation#23]
From what I can see, this IRI is associated with 3 subjects but it should only be one, correct?  Can you explain?
![Screen Shot 2020-02-07 at 12 41 06 PM](https://user-images.githubusercontent.com/6580029/74064269-2bb6fc80-49a7-11ea-9512-7c213ce94be9.png)

**Comment by tgbugs** [comment]
You are correct. This looks like it is because wasDerivedFromSubject is still using sample_id instead of the compound primary key which combines sample_id and subject_id. Will fix asap.

**Comment by tgbugs** [comment]
Fixed via a5c7c17.
