### ISSUE TITLE
Adding a Sheet Column

### ISSUE THREAD

**Issue by tmsincomb** [SciCrunch/sparc-curation#39]
Duplicate the behavior of Pandas to handle adding a column.

**Comment by tgbugs** [comment]
Changes will need to be made in https://github.com/tgbugs/pyontutils/blob/master/pyontutils/sheets.py.

**Comment by tgbugs** [comment]
Similar issue when trying to append rows beyond the end of the sheet e.g. when running `spc sheets update Organs --export-file curation-export.json` except that in that case it fails when trying to append, and then the next time will give an IndexError.

**Comment by tgbugs** [comment]
[`Sheet.update`](https://github.com/tgbugs/pyontutils/blob/master/pyontutils/sheets.py#L651-L666)is the first method that I forgot. And then I didn't actually read the [docstring](https://github.com/tgbugs/pyontutils/blob/master/pyontutils/sheets.py#L641-L644) on `Sheet.values.setter` which explicitly says that it won't extend the columns/rows.

**Comment by tgbugs** [comment]
I think this is fixed. If the issue remains open another issue in pyontutils.
