### ISSUE TITLE
always use idlib.Pio.uri_api_int as the identifier for protocols if it is available

### ISSUE THREAD

**Issue by tgbugs** [SciCrunch/sparc-curation#51]
Dereferencing dois from the metadata is a time expensive operation. It is much faster to embed the dois as metadata about the protocol and make it accessible via hasDoi.

**Comment by jgrethe** [comment]
Currently I am getting this information from:
'meta'.'protocol_url_or_doi'[*].'id'

Will this be changing?  Perhaps have one element for the doi explicitly instead of mashing url and doi together like with contributors:
'contributors'[*].'contributor_orcid_id'.'id'

**Comment by tgbugs** [comment]
Yes, in the preview I have made it so that the doi will have its own field if it is available. If there isn't another stable id like the protocols.io id (e.g. if it was a publication doi that we were provided) then the doi will still be used as the `id` but will also be present under `doi`. An example of the embedded json structure is below. Note that right at the moment it could just be an object, but I'm going to convert it so that protocol_url_or_doi is always a list. This is also in the context of the protcur.json output, which is has a jsonld format by default, I think that we need an array of protocols like we have an array of datasets, the issue is that the protocol identifier information comes from many places instead of just one, so I'm still thinking about the best way to handle this.

```json
          "protocol_url_or_doi": [{
            "doi": "https://doi.org/10.17504/protocols.io.ba8qihvw",
            "id": "https://www.protocols.io/api/v3/protocols/31728",
            "label": "Cardiac Action Potential Protocol",
            "system": "Pio",
            "type": "identifier",
            "uri_human": "https://www.protocols.io/view/cardiac-action-potential-protocol-ba8qihvw"
          }],
```

**Comment by jgrethe** [comment]
OK - let me know when this gets pushed as I will need to update the transform.

**Comment by tgbugs** [comment]
Done.
