### ISSUE TITLE
"U01" awards are valid SPARC awards  code is not recognizing 

### ISSUE THREAD

**Issue by ankap2** [SciCrunch/sparc-curation#68]
https://scicrunch.org/SPARC/Any/search?q=U01DK116317&l=U01DK116317
'U01DK116317' does not match '^OT|^U18';

**Comment by tgbugs** [comment]
Fixed by https://github.com/SciCrunch/sparc-curation/commit/8088a717b837e84f1dbd82d04ac2d56bd7797dae. That regex should also catch issues with `OT20D` vs `OT2OD` now.
