### ISSUE TITLE
Curation Export: Unpublished dataset showed as published

### ISSUE THREAD

**Issue by deepali-2018** [SciCrunch/sparc-curation#76]
From the curation export : https://doi.org/10.26275/6paz-gj9j is published, but Datacite information is missing for this DOI. 
Pennsieve API shows DOI status as UNPUBLISHED.

**Comment by tgbugs** [comment]
@deepali-2018 what was the solution?

**Comment by deepali-2018** [comment]
@tgbugs : After checking with @ankap2  confirmed that it was a test dataset
that was published for the steering comity meeting and retracted
afterward.  The owner retracted from publication  and it was deleted from
the public SPARC portal. It is sitting on Pennsieve right now. While
preprocessing this dataset I am tagging it with datacite error.
