### ISSUE TITLE
sympathetic ganglion children

### ISSUE THREAD

**Issue by SciCrunch-Synapse** [SciCrunch/sparc-curation#80]
This Github issue is synchronized with Zendesk:

**Ticket ID:** [#43424](https://scicrunch.zendesk.com/agent/tickets/43424)
**Requester:** mmartone@ucsd.edu
**Community Name:** fdi_lab
**URL:** 

**Original ticket description:**

<blockquote><div class="zd-comment" dir="auto"><p dir="auto">From: Maryann Martone &lt;<a href="mailto:mmartone@ucsd.edu" rel="noreferrer">mmartone@ucsd.edu</a>&gt;
<br>Phone: 
<br>Location: San Diego, United States
<br>URL: <a href="https://scicrunch.org/sawg/interlex/view/ilx_0730966" target="_blank" rel="nofollow noreferrer">https://scicrunch.org/sawg/interlex/view/ilx_0730966</a>
<br>Department: </p>

<p dir="auto">sympathetic ganglion has a bunch of children that don't seem like they should be children.  I can't see hos an interganglionic segment can be a ganglion.  It would help if the intergangionic segments had definitions.</p>

<p dir="auto">----
<br>Zopim
<br><a href="https://www.zopim.com" target="_blank" rel="nofollow noreferrer">https://www.zopim.com</a></p></div></blockquote>

**Comment by tgbugs** [comment]
@jgrethe these should be on the NIF-Ontology repo not here.
