### ISSUE TITLE
Paxinos spinal cord atlas import

### ISSUE THREAD

**Issue by SciCrunch-Synapse** [SciCrunch/sparc-curation#81]
This Github issue is synchronized with Zendesk:

**Ticket ID:** [#43443](https://scicrunch.zendesk.com/agent/tickets/43443)
**Requester:** mmartone@ucsd.edu
**Community Name:** fdi_lab
**URL:** 

**Original ticket description:**

<blockquote><div class="zd-comment" dir="auto"><p dir="auto">From: Maryann Martone &lt;<a href="mailto:mmartone@ucsd.edu" rel="noreferrer">mmartone@ucsd.edu</a>&gt;
<br>Phone: 
<br>Location: San Diego, United States
<br>URL: <a href="https://scicrunch.org/sawg/interlex/view/ilx_0772919?searchTerm=PAXSPN" target="_blank" rel="nofollow noreferrer">https://scicrunch.org/sawg/interlex/view/ilx_0772919?searchTerm=PAXSPN</a>
<br>Department: </p>

<p dir="auto">I don't like the solution of adding all of the terms requested by Janet Keast through an import of the Paxinos spinal cord atlas.  First of all, the definition or notes doesn't say anything at all about what paxspn means.  Second, if I want to annotate to the dorolateral fasciculus generically, I wouldn't use this term because it is specifically found in the Paxinos atlas.  </p>

<p dir="auto">----
<br>Zopim
<br><a href="https://www.zopim.com" target="_blank" rel="nofollow noreferrer">https://www.zopim.com</a></p></div></blockquote>

**Comment by tgbugs** [comment]
Should be on NIF-Ontology not here.
