### ISSUE TITLE
Link to example query to get model version is broken

### ISSUE THREAD

**Issue by dbrnz** [SciCrunch/sparc-curation#92]
<img width="1030" alt="Screenshot 2022-12-19 at 11 36 42 AM" src="https://user-images.githubusercontent.com/239220/208322917-4020c6c7-bd44-4511-955a-c043edc4ef06.png">

<img width="854" alt="Screenshot 2022-12-19 at 11 35 02 AM" src="https://user-images.githubusercontent.com/239220/208322933-755d8bf5-8b5e-480c-a266-9dd6e23b77d2.png">

<img width="624" alt="Screenshot 2022-12-19 at 11 38 34 AM" src="https://user-images.githubusercontent.com/239220/208323029-f9657040-6186-4709-aa6e-292339be9cc8.png">

**Comment by tgbugs** [comment]
Unfortunately there are multiple audiences and locations where the changelog needs to function, only one of which is github. The relative link in this case points to a symlink, which github does not resolve. We might be able to fix this in the future by rewriting the links when we build the sckan docker images.

https://github.com/dear-github/dear-github/issues/156

**Comment by dbrnz** [comment]
Separate to the symbolic link, the URL behind the `example query` text appears to end with two colons, hence the 404 error:

<img width="677" alt="Screenshot 2022-12-19 at 11 06 12 PM" src="https://user-images.githubusercontent.com/239220/208400483-c838cca9-17d2-41dd-bfce-c77757872ec0.png">

**Comment by tgbugs** [comment]
Ugh, this is another bug in github, or rather in https://github.com/wallyqs/org-ruby which is used internally to generate the html version. The `::` is syntax that indicates an internal reference, `#internal` fragments work from the same file, but not from another file. I'll see if I can find a way around the issue. The best option is probably for me to render the changelog to our ontology docs where all of these issues are resolved and where I also fix the github links. The file isn't there right now, but it would wind up at http://ontology.neuinfo.org/docs/sparc-curation/docs/sckan/CHANGELOG.html.

**Comment by tgbugs** [comment]
Ok. I have updated all our documentation and in the processes made the changelog a bit fancy so we can see which releases are/were `RC` and which one gets promoted to `PROD` and when that happened. I'll probably also stick some prospective stuff in there as well in the future.

Hopefully this will make it easier to keep track of everything, and as a bonus the links work and go directly to the code blocks as intended now.

http://ontology.neuinfo.org/docs/sparc-curation/docs/sckan/CHANGELOG.html
