### ISSUE TITLE
Please provide links to sample Cypher queries for getting SCKAN version information

### ISSUE THREAD

**Issue by dbrnz** [SciCrunch/sparc-curation#93]
For both SCKAN as an entity and for individual connectivity models within SCKAN.

If nothing else, please provide a TOC and index to the [over 5,500 line document](https://github.com/SciCrunch/sparc-curation/blob/master/docs/queries.org) that may have this information!

**Comment by tgbugs** [comment]
https://github.com/SciCrunch/sparc-curation/blob/master/docs/queries.org#embedded-load-provenance-record

**Comment by dbrnz** [comment]
Thanks -- things work!
