### ISSUE TITLE
align/normalize wasDerivedFrom (and related) columns from manifests when they refer to other dataset ids

### ISSUE THREAD

**Issue by tgbugs** [SciCrunch/sparc-curation#97]
also think about how to get this to the portal

the equivalent dataset to dataset relationship would be useful in related identifiers (note that datacite already has the IsDerivedFrom relation type)

**Comment by jgrethe** [comment]
Also need to bring this discussion into the larger manifest discussion initiated by DAT

**Comment by tgbugs** [comment]
I'm drafting a lengthy email in that thread.
